version: "3.5"

networks:
  host-net:
    driver: bridge

  zabbix:
    external: false

services:
  # https://hub.docker.com/r/zabbix/zabbix-server-mysql/
  zabbixserver:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      - DB_SERVER_HOST=172.16.16.104
    env_file:
      - ./env_files/.env_db_mysql
      - ./env_files/.env_srv
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/zabbix/server/galertscripts:/usr/lib/zabbix/alertscripts
      - /dockerdata/zabbix/server/gexternalscripts:/usr/lib/zabbix/externalscripts
      - /dockerdata/zabbix/server/gmodules:/var/lib/zabbix/modules
      - /dockerdata/zabbix/server/genc:/var/lib/zabbix/enc
      - /dockerdata/zabbix/server/gssh_keys:/var/lib/zabbix/ssh_keys
      - /dockerdata/zabbix/server/gssl/certs:/var/lib/zabbix/ssl/certs
      - /dockerdata/zabbix/server/gssl/keys:/var/lib/zabbix/ssl/keys
      - /dockerdata/zabbix/server/gssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      # - /dockerdata/zabbix/server/gsnmptraps:/var/lib/zabbix/snmptraps
      - /dockerdata/zabbix/server/gmibs:/var/lib/zabbix/mibs
      - /dockerdata/zabbix/server/gexport:/var/lib/zabbix/export
    volumes_from:
      - zabbixsnmptraps
    networks:
      - host-net
      - zabbix
    ports:
      - 10051:10051
    depends_on:
      - zabbixsnmptraps

  zabbixweb:
    # https://hub.docker.com/r/zabbix/zabbix-web-apache-mysql/
    image: zabbix/zabbix-web-apache-mysql:latest
    env_file:
      - /dockerdata/zabbix/env_vars/.env_db_mysql
      - /dockerdata/zabbix/env_vars/.env_web
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: always
    networks:
      - host-net
      - zabbix
    ports:
      - 8880:8080
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/zabbix/web/etc/ssl/apache2:/etc/ssl/apache2:ro
      - /dockerdata/zabbix/web/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro

  zabbixagent:
    # https://hub.docker.com/r/zabbix/zabbix-agent2/
    image: zabbix/zabbix-agent:latest
    env_file:
      - ./env_files/.env_agent
    restart: always
    networks:
      - zabbix
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/zabbix/agent2/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /dockerdata/zabbix/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /dockerdata/zabbix/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /dockerdata/zabbix/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    depends_on:
      - zabbixserver

  zabbixsnmptraps:
    # https://hub.docker.com/r/zabbix/zabbix-agent2/
    image: zabbix/zabbix-snmptraps:latest
    environment:
      - ZBX_HOSTNAME=zabbixsnmptraps
      - ZBX_SERVER_HOST=zabbixserver
      - PHP_TZ="Europe/Zurich"
    restart: always
    networks:
      - zabbix
    ports:
      - 162:1162/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw

#db:
#    build: .
#    image: mariadb:latest
#    restart: always
#    environment:
#        - MARIADB_ROOT_PASSWORD=zabbix
#        - MARIADB_USER=zabbix
#        - MARIADB_PASSWORD=Zabbix123!
#        - MARIADB_DATABASE=zabbix
#    networks:
#        - zabbix
#    volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - /dockerdata/zabbix/db:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8884:80
    environment:
      - PMA_HOST=172.16.16.104
      - PMA_PORT=3306
      - PMA_USER=zabbix
      - PMA_PASSWORD=Zabbix123!
    networks:
      - host-net
      - zabbix
    volumes:
      - /etc/localtime:/etc/localtime:ro

secrets:
  MYSQL_USER:
    file: /dockerdata/zabbix/env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: /dockerdata/zabbix/env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: /dockerdata/zabbix/env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: /dockerdata/zabbix/env_vars/.MYSQL_ROOT_PASSWORD
